//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASOC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENT_STATUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CURRENT_STATUS()
        {
            this.STATUS_COSTS = new HashSet<STATUS_COSTS>();
        }
    
        public decimal ID { get; set; }
        public decimal ID_COMPLECT { get; set; }
        public decimal ID_STATUS { get; set; }
        public System.DateTime DATE_STATUS { get; set; }
        public string REASON { get; set; }
    
        public virtual COMPONENT COMPONENT { get; set; }
        public virtual STATUS STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STATUS_COSTS> STATUS_COSTS { get; set; }
    }
}
