//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASOC.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMPONENT> COMPONENT { get; set; }
        public virtual DbSet<CURRENT_STATUS> CURRENT_STATUS { get; set; }
        public virtual DbSet<MODEL> MODEL { get; set; }
        public virtual DbSet<PRICE> PRICE { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<STATUS_COSTS> STATUS_COSTS { get; set; }
        public virtual DbSet<TYPE> TYPE { get; set; }
    }
}
