//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASOC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICE
    {
        public decimal ID { get; set; }
        public decimal ID_MODEL { get; set; }
        public System.DateTime DATE_ADD { get; set; }
        public decimal COAST { get; set; }
    
        public virtual MODEL MODEL { get; set; }
    }
}
