//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASOC.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_COSTS
    {
        public decimal ID { get; set; }
        public decimal ID_CURRENT { get; set; }
        public string COSTS { get; set; }
    
        public virtual CURRENT_STATUS CURRENT_STATUS { get; set; }
    }
}
